name = "jonsson-photoblog"
main = "src/index.js"
compatibility_date = "2024-01-01"
compatibility_flags = ["nodejs_compat"]

[build]
command = ""

[build.upload]
format = "modules"

[[d1_databases]]
binding = "DB"
database_name = "jonsson-photoblog-prod"
database_id = "2e3d3aea-1cfc-4f4a-a821-2eb7a01ce65e"

[env.production]
name = "jonsson-photoblog-prod"

[[env.production.d1_databases]]
binding = "DB"
database_name = "jonsson-photoblog-prod"
database_id = "2e3d3aea-1cfc-4f4a-a821-2eb7a01ce65e"

[env.staging]
name = "jonsson-photoblog-staging"

[vars]
ENVIRONMENT = "development"

[env.production.vars]
ENVIRONMENT = "production"

[env.staging.vars]
ENVIRONMENT = "staging"