name = "jonsson-homepage"
main = "src/index.js"
compatibility_date = "2024-01-01"
compatibility_flags = ["nodejs_compat"]

# Custom domain configuration  
routes = [
  "jonsson.io/*",
  "www.jonsson.io/*"
]

# Static assets configuration
assets = { directory = "./public", binding = "ASSETS" }

# D1 Database configuration
[[d1_databases]]
binding = "DB"
database_name = "jonsson-photos-db"
database_id = "66dd8c3c-125f-4627-a0b7-810a65dd7182"

[build]
command = ""

[vars]
ENVIRONMENT = "development"
# B2 credentials are loaded from .dev.vars file automatically
# B2_APPLICATION_KEY_ID = "your-key-id"
# B2_APPLICATION_KEY = "your-application-key"
# B2_BUCKET_ID = "your-bucket-id"
# B2_BUCKET_NAME = "your-bucket-name"

[env.production.vars]
ENVIRONMENT = "production"
# For production, set these as secrets:
# wrangler secret put B2_APPLICATION_KEY_ID
# wrangler secret put B2_APPLICATION_KEY
# wrangler secret put B2_BUCKET_ID
# wrangler secret put B2_BUCKET_NAME

[env.staging.vars]
ENVIRONMENT = "staging"